// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxCmygu7PXlGFB0cXSEVGzyfgoE-LJ3uY',
    appId: '1:898585044292:web:4832a480599e63b1212311',
    messagingSenderId: '898585044292',
    projectId: 'sri-route',
    authDomain: 'sri-route.firebaseapp.com',
    storageBucket: 'sri-route.firebasestorage.app',
    measurementId: 'G-XPQYDW13ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8cOLHOAxGq5jUOJRv23jdKwN8dDgTCw4',
    appId: '1:898585044292:android:48b031ab8ae59624212311',
    messagingSenderId: '898585044292',
    projectId: 'sri-route',
    storageBucket: 'sri-route.firebasestorage.app',
  );
