name: sri_route
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.16.0
  firebase_core: ^2.4.1
  google_sign_in: ^6.1.4
  shared_preferences: ^2.2.0
  firebase_storage: ^11.5.1
  panorama: ^0.4.1
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.0.15
  google_maps_flutter: ^2.5.0  # Added Google Maps package
  table_calendar: ^3.0.9
  flutter_signin_button: ^2.0.0
  intl: ^0.18.1  # Add this if it's not already there
  cloud_firestore: ^4.13.1
  http: ^1.3.0
  google_fonts: ^6.1.0
  url_launcher: ^6.1.0
  image_picker: ^1.0.4
  firebase_app_check: ^0.2.1+15
  geolocator: ^10.0.0
  geocoding: ^2.1.1
  permission_handler: ^11.4.0
  permission_handler_android: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0  # Add this line

dependency_overrides:
  motion_sensors:
    path: ./patches/motion_sensors+0.1.0

flutter:
  uses-material-design: true
  
  # Assets section for the image files
  assets:
    - assets/sambodhi_pagoda.jpg
    - assets/jami_ul_alfar.jpg
    - assets/sri_dalada_maligawa.jpg
    - assets/logo.jpeg
    - assets/sri_dalada.png
    - assets/basilica.png
    - assets/red_mosque.png
    - assets/map.png
    - assets/user_profile.png
    - assets/header_bg.png
    - assets/welcomepage1.png
    - assets/welcomepage2.png
    - assets/welcomepage3.png
    - assets/welcomepage4.png
    - assets/welcomepage5.png
    - assets/sacred_heart_church.jpeg
    - assets/kataragama_devalaya.jpeg
    - assets/SDGP_app_logo.png

