name: settings
description: "A Flutter application for managing user settings and preferences."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0 # Adjust if your Flutter SDK version differs

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0 # Ensure this line is present and properly indented

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true