name: religious_sites
description: "A Flutter app to explore religious sites in Sri Lanka."

# Prevents accidental publishing to pub.dev (remove if you intend to publish)
publish_to: 'none'

# Versioning: 1.0.0 is the initial version, +1 is the build number
version: 1.0.0+1

# Specifies the Flutter SDK version range your app supports
environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons (optional, included by default)
  cupertino_icons: ^1.0.8

  # Google Fonts for enhanced typography
  google_fonts: ^6.1.0

  # URL Launcher for opening Google Maps links
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices
  flutter_lints: ^5.0.0

flutter:
  # Ensures Material Icons are included for use in the app
  uses-material-design: true

  # Define all assets (images) used in the app
  assets:
    - assets/images/Gangaramaya_Temple.jpg 
    - assets/images/Gangaramaya_Temple.jpg
    - assets/images/Kelaniya_Raja_Maha_Vihara.jpg
    - assets/images/Asokaramaya_Temple.jpg
    - assets/images/Vajira_Sri_Temple.jpg
    - assets/images/Isipathanaramaya_Temple.jpg
    - assets/images/St_Anthony’s_Shrine.jpg
    - assets/images/Wolvendaal_Church.jpg
    - assets/images/St_Lucia’s_Cathedral.jpg
    - assets/images/All_Saints’_Church.jpg
    - assets/images/St_Andrew’s_Scots_Kirk.jpg
    - Sri_Kailawasanathan_Swami_Devasthanam.jpg
    - New_Kathiresan_Kovil.jpg
    - 
    -
    -
    -
    -
    -
    -
    -
    -
    -
    -
    -
    -
    -
    -
    -
    -
    -

    -
    -
    -
    
  

  # Uncomment and configure custom fonts here if you want to use local font files
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700